---
title: "Main Text Statistics"
output:  
      html_document: 
                toc: true
                toc_depth: 3
                toc_float: true

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE)
```

```{r, echo=FALSE}
source("code/extra/utils.R")
reload_source()

```

```{r loadLinelist, echo=FALSE}


# dat_2014 <- load_and_clean_2014_data() %>% mutate(wave="2014")
# dat_2015 <- load_and_clean_2015_data()%>% mutate(wave="2015")
# dat_2017 <- load_and_clean_2017_data()%>% mutate(wave="2016/2017")
#
# master_dat <- bind_rows(dat_2014,dat_2015,dat_2017)

# saveRDS(master_dat,file="data/generated_data/master_linelist_final.rds")

master_dat <- read_rds("data/generated_data/master_linelist_final.rds") 
missing <- filter(master_dat,is.na(onset_date_imp)|is.na(admin2Name)) %>%
              select(wave,onset_date_imp,admin2Name)

#load shapefile
my_map <- read_sf("data/raw_data/ssd_admbnda_adm2_200k_ssnbs_20160114.shp") 

#bring in population data
worldpop_dat <- read_csv("data/raw_data/SSD15adjv3_tif+SSD-HDX-Borders_adm2_zonal.csv")

```


```{r loadiomdata, echo=FALSE}

#get iom dataset ready
final_iomdata <- read_csv("data/generated_data/IOM_longdata.csv") %>%
        #split 2015/2016 into two years (will re-add below)
        mutate(number = ifelse(period=="2015/2016",number/2,number))
final_iomdata <- final_iomdata %>% 
        mutate(period = recode(period,
                               `2013/2014` = "2014",
                               `2015/2016` = "2015",
                               `2017JanJun`="2017",
                               `2017JulDec`="2017"
                                )) %>%
        # re-add 2016
        bind_rows(filter(final_iomdata,period=="2015/2016")) %>%
        mutate(period = recode(period,
                               `2015/2016` = "2016")) %>%
        #edit name of county
        mutate(
                origin=ifelse(countryOrigin=="South Sudan",countyOrigin,countryOrigin),
                origin= ifelse(origin =="Aweil Center","Aweil Centre",origin),
                origin= ifelse(origin =="Canal (Khorfulus)","Canal/Pigi",origin),
                origin= ifelse(origin =="Ikwoto","Ikotos",origin),
                origin= ifelse(origin =="Kajo-Keji","Kajo-keji",origin),
                origin= ifelse(origin =="Luakpiny (Nasir)","Luakpiny/Nasir",origin),
                origin= ifelse(origin =="Raja","Raga",origin),
                origin= ifelse(origin =="Terkeka","Terekeka",origin),
                
                assess= countyAssessed,
                assess= ifelse(assess =="Aweil Center","Aweil Centre",assess),
                assess= ifelse(assess =="Canal (Khorfulus)","Canal/Pigi",assess),
                assess= ifelse(assess =="Kajo-Keji","Kajo-keji",assess),
                
                count = number
        ) %>% 
        select(period,origin, assess,count,countryOrigin, admin2Pcod) %>% 
        group_by(period,origin, assess,countryOrigin,admin2Pcod) %>%
        summarize(count=sum(count))  %>% ungroup(period)%>%
        filter(period!="2018JanApr" & count !=0)%>%
        filter(origin!=assess) %>%
        filter(origin != "Other (Specify)")

```


```{r loadOCVdata, echo=FALSE}

#bring in ocv data
raw_ocv_dat <- read_xlsx("data/raw_data/ocv_summary_south_sudan.xlsx",na = c("","?"))  %>%
        rename(admin2Name = County,doses_r1 = `Doses administered 1st round`) %>%
        mutate(date_r1 = as.Date(`Start\r\n1st round`,origin="1970-1-1"))%>%
        mutate(doses_r2=as.numeric(`Doses administered 2nd round`))%>%
        #calculate coverage
        left_join(worldpop_dat %>% select(admin2Name,SUM)) %>%
        mutate(r1_coverage = doses_r1/SUM)



```

```{r loadRainfall, echo=FALSE}

chrps_rainfall_2010_2018 <- read_csv("data/raw_data/ssd_chrps_county/chrps_counties_dailyrainfall_2010_2018.csv")

```

```{r loadMLVA, echo=FALSE}
mlva_resistance <- read_csv("data/raw_data/mlva_resistance_mlq.csv") %>%
  rename(sampleID = `N?CNRVC`)

```


## Abstract

```{r abstract}

table(master_dat$wave)

#see results for comparison of attack rates and statistics on vaccination campaigns

```


## Methods 

### IOM data

```{r iomdata}

#counties in the iom dataset
iom_counties <- unique(final_iomdata$assess)
all_counties <- my_map$admin2Name
table(all_counties %in% iom_counties)

#counties affected by cholera
cholera_counties <- master_dat %>% 
                        group_by(admin2Name) %>%
                        summarize(cases=n()) %>%
                        mutate(assessed=admin2Name %in% iom_counties) %>%
                        filter(!is.na(admin2Name))
cholera_counties %>% summarise(
                        cholera_counties=n(),
                        assessed_counties=sum(assessed),
                        allcases=sum(cases),
                        assessedcases=sum(cases*assessed),
                        percent=assessedcases/allcases
                               ) 


```

### Serial Interval

```{r serialinterval-mcmc}

#load previously run fits
fit2014<- read_rds("data/generated_data/fit2014.rds")
fit2015<- read_rds("data/generated_data/fit2015long.rds")
fit2016<- read_rds("data/generated_data/fit2016.rds")

# to run the full stan code
# source("code/extra/run_stan_SImodel.R")

getDraws <- function(fitting,iter,warmup,chains){
    
    df <- data.frame()

    for (j in 1:chains){

        #turn list into data.frame
        newChain <-as.data.frame(fitting@sim$samples[[j]])
        #remove warm-up samples
        newChain<- newChain[(warmup+1):iter,]
        #append new chain to previous ones
        df <- bind_rows(df,newChain)
    }
    return(df)
    
}

#organize MCMC data into dataframe
draws2014 <- getDraws(fit2014,iter=5000,warmup=1000,chains=4)
draws2015 <- getDraws(fit2015,iter=100000,warmup=1000,chains=4) #note the larger number of iterations chosen
draws2016 <- getDraws(fit2016,iter=5000,warmup=1000,chains=4)

# thin due to autocorrelation of MCMC
final2014 <- draws2014[seq(1,nrow(draws2014),10),] %>%
                mutate(year=2014)
final2015 <- draws2015[seq(1,nrow(draws2015),10),]%>%
                mutate(year=2015)
final2016 <- draws2016[seq(1,nrow(draws2016),10),]%>%
                mutate(year=2016)

#bring together in one dataset
pdata<- bind_rows(final2014,final2015,final2016) %>%
        mutate(meanSI=shape*scale,
               R0=exp(logR),
               year=factor(year)
               ) 

#calculate mean and variances
meanSD<- pdata %>%        mutate(meanGT=shape*scale,
                                 varGT= shape*(scale^2)
                                 ) %>% 
                          mutate(sdGT=sqrt(varGT))

p1 <- meanSD %>% ggplot(aes(x=meanGT,col=year))+ geom_density()
p2 <- meanSD %>% ggplot(aes(x=sdGT,col=year))+ geom_density()

plot_grid(p1,p2)


meanSD <-meanSD%>% 
    group_by(year) %>% summarize( mean=mean(meanGT),
                                  sd=median(sdGT),
                                  var=median(varGT)

                                 ) 

meanSD

```


```{r serialinterval-gendata, echo=FALSE}

# #save the draws for plots
# # write_csv(pdata,"data/generated_data/pdata_final.csv")
# 
# #original phelps estimates
# mean_si<- 3.7 #phelps estimate is 3.7 (2.9-4.7)
# sd_si <- 2.2
# 
# #generate discrete SI distributions for dlnm model
# discreteDF <- data.frame(days=0:10) %>%
#         mutate(
#                `2015`=EpiEstim::discr_si(days, as.numeric(meanSD[2,2]),
#                                  as.numeric(meanSD[2,3])),
#                `2016`=EpiEstim::discr_si(days, as.numeric(meanSD[3,2]),
#                                  as.numeric(meanSD[3,3])),
#                Phelps=EpiEstim::discr_si(days, mean_si, sd_si)
#                ) %>%
#         mutate(
#                `2015`=`2015`/sum(`2015`),
#                `2016`=`2016`/sum(`2016`),
#                Phelps=Phelps/sum(Phelps)
#                ) %>%
#         gather(Estimate,value,-days)
# 
# # write_csv(discreteDF,"data/generated_data/discreteDF_final.csv")


```


## Results

See table 1 for county and state specific results per wave


```{r dates}

#OVERALL

#get dates of confirmed cases
master_dat %>% filter(culture_result=="1") %>%
        group_by(wave)%>%
        summarize(first=min(onset_date_imp, na.rm = TRUE),
                  last=max(onset_date_imp, na.rm = TRUE)
                  )

#number of cases and counties
master_dat %>% group_by(wave)%>%
                summarize(
                                counties=length(unique(admin2Name)),
                                cases=n(),
                                deaths=sum(died,na.rm = TRUE),
                                min=min(onset_date_imp,na.rm = TRUE),
                                max=max(onset_date_imp,na.rm = TRUE),
                                diff=round(as.numeric(max-min)/7,1)
                          ) %>%
                mutate( btw=round(as.numeric(min-lag(max,1))/7,1))

#cases missing in the table
master_dat %>% filter(is.na(admin2Name)) %>%
        select(wave)


#children under 5
master_dat %>%
        mutate(under5 = ifelse(age<5,1,0)
        ) %>% group_by(wave,under5)%>%
                # filter(!is.na(under5))%>%
                summarize(cases=n()
                          )%>%
                group_by(wave)%>%
                mutate(total=sum(cases),
                       percent=cases/total*100
                       )

#sex
master_dat %>% group_by(wave,sex)%>%
                summarize(cases=n(),
                          )%>%
                group_by(wave)%>%
                mutate(total=sum(cases),
                       percent=cases/total*100
                       )


# 2014
# upper nile state
table(filter(master_dat,state=="UNS" & wave=="2014")$admin2Name)


#2015

filter(master_dat, admin2Name=="Juba" & wave=="2015") %>%
          summarize(cases=n(),
                    percent=cases/1818,
                    first=min(onset_date_imp,na.rm = TRUE),
                    last=max(onset_date_imp,na.rm = TRUE)
                    )


# 2016 & 2017
#first caese in Juba (weird case in Rubkhona)
master_dat %>% filter(wave=="2016/2017")%>%
        filter(admin2Name=="Juba")%>%
        filter(onset_date_imp==min(onset_date_imp, na.rm = TRUE)) %>% select(onset_date_imp)



#ayod
ayod <- master_dat %>% filter(admin2Name=="Ayod") %>%
        filter(wave=="2016/2017") 
ayod %>%        summarize(count=n(),
                  deaths=sum(died),
                 min= min(onset_date_imp,na.rm = TRUE),
                 max=max(onset_date_imp,na.rm = TRUE),
                 count/(as.numeric(max-min)/7)
                 )

ayod %>% group_by(isoweek(onset_date_imp)) %>%
          mutate( week = floor_date(onset_date_imp - 1, "weeks") + 1) %>%
          summarize(count=n())


1595+1284+397

```

### Vaccination Campaigns

```{r vaccination1}

# calculate the first week and last case for each wave
first <- master_dat %>% group_by(admin2Name,wave)%>%
             summarize(fdate=min(onset_date_imp,na.rm = TRUE)) 

last <- master_dat %>%
        group_by(admin2Name,wave) %>%
        summarize(ldate=max(onset_date_imp,na.rm = TRUE))

#put the number of cases at a weekly level to determine the peak week
masterfinal <- master_dat %>% 
        mutate( week = floor_date(onset_date_imp - 1, "weeks") + 1) %>%
        group_by(wave,week, admin2Name) %>%
        summarize(cases=n()) %>%
        filter(!is.na(week) & !(is.na(admin2Name))) 

peak <- masterfinal %>%
        group_by(admin2Name,wave) %>%
        filter(cases==max(cases)) %>%
        select(admin2Name,wave,week,cases) %>%
        arrange(week,admin2Name)%>%
        rename(peakWk=week) %>%
        group_by(admin2Name,wave) %>%
        summarize(peakWk=mean(peakWk),
                   cases=mean(cases)) %>%
        mutate(
                  peakWkStart=peakWk,
                  peakWkEnd=peakWkStart+6
                  )

#########PARAGRAPH: In addition to case management, surveillance, and WASH intervention.....

# Total doses
sum(raw_ocv_dat$doses_r1) +sum(raw_ocv_dat$doses_r2,na.rm = TRUE)
# of campaigns
nrow(raw_ocv_dat)
table(raw_ocv_dat$Year,useNA = "always")
#of cholera counties with campaigns
table(cholera_counties$admin2Name %in% unique(raw_ocv_dat$admin2Name) )
sum(raw_ocv_dat$admin2Name=="Juba")
#range of doses reached
summary(raw_ocv_dat$doses_r1)
#administrative coverage (copy and paste into console)
summary(raw_ocv_dat$`Admin coverage \r\n1st round`)
#county level coverage
summary(raw_ocv_dat$r1_coverage)


```

```{r vaccination2}
#prep OCV data for additional calculations
ocv_dat <- raw_ocv_dat%>% 
        #assign waves to each campaign
        # select(No.,admin2Name,date_r1,r1_coverage) %>%
        filter(!is.na(date_r1)) %>%
        mutate(yr=as.character(year(date_r1)),
               wave=ifelse(yr=="2016" | yr=="2017","2016/2017",yr))%>%
        arrange(date_r1,admin2Name)%>%
        #match with peak and last case data
        left_join(peak, c("admin2Name","wave")) %>%
        left_join(last, c("admin2Name","wave")) %>%
        ## TTL time to last case, TTP time to start of peak week
        mutate(TTL=as.numeric(date_r1-ldate),
                TTP=as.numeric(date_r1-peakWk)) %>%
        #label as juba vs not
        # select(No.,admin2Name,wave,date_r1,TTL,TTP,r1_coverage) %>%
        mutate(County=ifelse(admin2Name=="Juba",
                             "Juba",
                             "Other Counties"))  %>%
        #match with first case
        left_join(first,by=c("admin2Name","wave")) %>%
        #timing declarations
        mutate(
              #reactive vs. non reactive
              campaignTiming1 = ifelse(date_r1>=fdate,"Reactive","Preemptive"),
              #before during or after peak
              campaignTiming2 = ifelse(date_r1>=peakWkStart,"During or After Peak","Before Peak"),
              campaignTiming3 = ifelse(date_r1>=peakWkStart & date_r1<=peakWkEnd,
                                       "During Peak",campaignTiming2),
              campaignTiming3 = ifelse(date_r1>peakWkEnd,
                                       "After Peak",campaignTiming3),
              #before or after the last case
              campaignTiming4 = ifelse(date_r1>ldate,
                                       "After Cases Disappeared",
                                       "Before Cases Disappeared"
                                       )



        )





#########PARAGRAPH: Among 25 campaigns conducted reactively (ie, in response to cases)..

#reactive campaigns
reactive <- ocv_dat %>% filter(date_r1>=fdate)
#campaigns in areas with cholera cases
nrow(reactive)
# filter(reactive,TTP<=6)
# sum(reactive$TTP<=6,na.rm = TRUE)
table(reactive$campaignTiming3,reactive$wave)

#assess how many campaigns occurred before the peak
# table(reactive$wave,reactive$TTP<=6)
table(reactive$campaignTiming3,reactive$wave)
# table(ocv_dat$TTP<0) #for the abstract
table(ocv_dat$campaignTiming3,useNA = "always") #for the abstract

# assess how many campaigns occurred after the last case
# table(reactive$wave,reactive$TTL>0)
table(ocv_dat$wave,ocv_dat$TTL>0)



# All five counties with vaccination campaigns in 2014 or 2015
# reported cases during the 2016–17 wave
vacc1415 <- ocv_dat %>% filter(wave %in% c(2014,2015)) %>% distinct(admin2Name)
chol1617 <- filter(master_dat,wave=="2016/2017") %>% distinct(admin2Name)
nrow(vacc1415)
vacc1415$admin2Name %in% chol1617$admin2Name


#calculate the attack rate
ardf <- master_dat %>% #masterfinal %>%  
        group_by(admin2Name,wave) %>%
        summarize(cases=n()) %>%
        left_join(select(worldpop_dat,admin2Name,SUM))%>%
        mutate(ARpercent=cases/SUM*100)%>%
        filter(!is.na(admin2Name))

#for each campaign
ocv_dat2<- ocv_dat %>%
        group_by(admin2Name,wave) %>%
        filter(date_r1==min(date_r1))%>%
        filter(r1_coverage==sum(r1_coverage))%>%
        filter(!is.na(TTP))  %>%
        select(-cases,-SUM)


#choose which outbreaks had an OCV campaign before or after the campaign
ardf2 <- ardf %>% left_join(ocv_dat2, by=c("admin2Name","wave")) %>%
        mutate(BeforePeak=ifelse(TTP<0,"Before Peak","After Peak"),
               BeforePeak=ifelse(is.na(TTP),"No Campaign",BeforePeak))

#calculate the raw ARR
ardf2 %>% group_by(BeforePeak) %>%
          summarize(cases=sum(cases),
                    pop=sum(SUM),
                    AR=cases/pop
                    ) %>%
          mutate(first(AR)/AR)

#graphic
ardf2 %>%  mutate(campaignTiming2=ifelse(is.na(campaignTiming2),
                                    "No campaign",campaignTiming2))%>%
        ggplot(aes(x=campaignTiming2,y=ARpercent,col=admin2Name=="Juba"))+
        geom_jitter(height=0,alpha=0.7)+
        scale_y_continuous(trans="log10")+xlab("Timing")+
        ylab("AR (%)")


#fit 1: Compare before and after peak (include peak week as after)
fit <-ardf2 %>% 
      mutate(campaignTiming2=ifelse(is.na(campaignTiming2),
                                    "No campaign",campaignTiming2)) %>%
        glm(data=., cases ~campaignTiming2 +offset(log(SUM)),family=poisson)
exp(fit$coefficients)
exp(confint(fit))


#fit 2: Compare before and after peak controlling for coverage and wave
fit2 <-ardf2 %>% 
      mutate(campaignTiming2=ifelse(is.na(campaignTiming2),
                                    "No campaign",campaignTiming2)) %>%
        glm(data=., cases ~campaignTiming2 +r1_coverage + wave+offset(log(SUM)),family=poisson)
exp(fit2$coefficients)
exp(confint(fit2))

#fit 3: Compare before and after peak (include peak week as before)
ardf3 <- ardf %>% left_join(ocv_dat2) %>%
        mutate(BeforePeak=ifelse(TTP<=6,"Before Peak","After Peak"),
               BeforePeak=ifelse(is.na(TTP),"No Campaign",BeforePeak))

fit3 <-ardf3 %>% 
        glm(data=., cases ~BeforePeak +offset(log(SUM)),family=poisson)
exp(-fit3$coefficients)
exp(-confint(fit3))

```


### The Role of Precipitation

```{r precipitation}

mapdf <- as.data.frame(read_sf("data/raw_data/ssd_admbnda_adm2_200k_ssnbs_20160114.shp")) %>%
        select(admin2Name,admin2Pcod)

rainfall_daily <- chrps_rainfall_2010_2018 %>%
  mutate(Date = as.Date(dates,format="%m/%d/%Y",origin="1970-1-1"),
         week = floor_date(Date - 1, "weeks") + 1) %>%
          left_join(mapdf, by="admin2Pcod") %>%
        mutate(month=month(Date)) %>%
        mutate(rainy= (month %in% c(4:11)))



rainfall_daily %>% filter(admin2Name=="Juba") %>%
        group_by(rainy)%>%
        summarize(precip=sum(avgDailyRainfall))%>%
        mutate(   percent=precip/sum(precip))

rainfall_daily %>% 
        group_by(rainy)%>%
        summarize(precip=sum(avgDailyRainfall))%>%
        mutate(   percent=precip/sum(precip))

```

### MLVA

```{r}

#MLVA dataframe
mlva_ssd <- mlva_resistance %>%
  filter(Country == "South Sudan") %>%
  rename(year = `Isolation Year`) %>%
  select(sampleID, year,
         MLVA_VC0147,
         MLVA_VC0437,
         MLVA_VC1457,
         MLVA_VC1650,
         MLVA_VCA0171,
         MLVA_VCA0283) %>%
  #reference id
  mutate(
    MLVA_VC0147 = MLVA_VC0147 -10 ,
    MLVA_VC0437 = MLVA_VC0437 - 7,
    MLVA_VC1457 = MLVA_VC1457 - 3,
    MLVA_VC1650 = MLVA_VC1650 - 7,
    MLVA_VCA0171 = MLVA_VCA0171 - 10,
    MLVA_VCA0283 = MLVA_VCA0283 - 18
  ) %>%
  rename(
    VC0147 = MLVA_VC0147 ,
    VC0437 = MLVA_VC0437,
    VC1457 = MLVA_VC1457 ,
    VC1650 = MLVA_VC1650,
    VCA0171 = MLVA_VCA0171,
    VCA0283 = MLVA_VCA0283
  ) %>%
  gather(site, distance, -c(sampleID,year)) %>%
  mutate(sampleID = factor(sampleID),
         distance = factor(distance))


distinct(mlva_ssd,sampleID,year) %>% group_by(year) %>%
          summarize(n())

```


### The Role of Population Movement in Cholera Dissemination

```{r displacement}

final_iomdata %>%   ungroup() %>%    
          summarize(count=sum(count))

final_iomdata %>%   group_by(period)%>%    
          summarize(count=sum(count))

final_iomdata %>%   group_by(countryOrigin)%>%    
          summarize(count=sum(count))

final_iomdata %>% filter(origin=="Juba") %>%
        group_by(period) %>%
        summarize(count=sum(count))

(7234-2458)/7234

```


## Discussion

```{r}


sum(reactive$doses_r1+reactive$doses_r2,na.rm = TRUE)
reactive %>% filter(campaignTiming3 %in% c("Before Peak","During Peak"))%>%
        summarize(sum(doses_r1+doses_r2,na.rm = TRUE))

round(100*73882 / 1805452,1)



```


